
'use server';

/**
 * @fileOverview An AI agent that identifies the top trending topics across various niches for a specific region,
 * including a full post plan for each.
 *
 * - getTopTrends - A function that returns a list of top trends with all details for a given region.
 * - TopTrendsInput - The input type for the getToptrends function.
 * - TopTrendsOutput - The return type for the getTopTrends function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { niches } from '@/lib/data';

const TopTrendsInputSchema = z.object({
  region: z.string().describe('The geographical region or country to get trends for.'),
});
export type TopTrendsInput = z.infer<typeof TopTrendsInputSchema>;

const TrendSchema = z.object({
    trendName: z.string().describe('The name of the emerging trend.'),
    niche: z.string().describe('The content niche this trend belongs to (e.g., Fashion, Gaming, Food).'),
    description: z.string().describe('A brief, one-sentence description of the trend and why it\'s popular.'),
    platform: z.string().describe('The primary social media platform where this trend is popular (e.g., TikTok, Instagram).'),
    viralityScore: z.number().min(0).max(100).describe('A score from 0-100 indicating the trend\'s current virality.'),
    isBreakoutTrend: z.boolean().describe('Set to true ONLY if this trend is experiencing explosive, rapid growth in the last 24-48 hours. Use this sparingly for only the most exceptional, fast-moving trends.'),
    hashtags: z.string().describe('A string of 3-5 relevant hashtags, separated by commas (e.g., #AIart, #generativeart, #digitalart).'),
    reasoning: z.string().describe('A detailed explanation of why the trend is rising, citing cultural context, events, or other factors.'),
    googleTrendsLink: z.string().describe('A full, working URL to the Google Trends page for a relevant keyword.'),
    viralAudioSound: z.string().optional().describe('The name or ID of a viral audio/sound associated with the trend, if applicable.'),
    postPlan: z.object({
        hook: z.string().describe('A captivating hook for the post.'),
        caption: z.string().describe('An engaging caption for the post.'),
        emojiCombo: z.string().describe('A creative combination of emojis for the post.'),
        suggestedPostFormat: z.string().describe('The suggested post format (e.g., Reel, meme, tweet).'),
    }).describe('A full AI-powered post plan for this trend.')
});

const TopTrendsOutputSchema = z.object({
  trends: z.array(TrendSchema).describe('A list of top-trending topics. There must be at least 2 trends for each requested niche.'),
});
export type TopTrendsOutput = z.infer<typeof TopTrendsOutputSchema>;
export type Trend = z.infer<typeof TrendSchema>;

const fallbackTrends: TopTrendsOutput = {
    trends: [
        {
            trendName: 'AI-Generated Art',
            niche: 'AI & Future Tech',
            description: 'Creators are using AI to generate surreal and stunning visuals, pushing the boundaries of creativity.',
            platform: 'Instagram',
            viralityScore: 92,
            isBreakoutTrend: true,
            hashtags: '#AIart, #generativeart, #digitalart',
            reasoning: 'Advances in text-to-image models have made high-quality AI art accessible to everyone, leading to a Cambrian explosion of creativity.',
            googleTrendsLink: 'https://trends.google.com/trends/explore?q=ai%20art',
            viralAudioSound: 'Metamorphosis - INTERWORLD',
            postPlan: {
                hook: 'I asked an AI to paint a dream...',
                caption: 'Exploring the surreal landscapes generated by AI. What does the future of art look like? #AIart',
                emojiCombo: '🤖🎨✨',
                suggestedPostFormat: 'Instagram Carousel Post',
            }
        },
        {
            trendName: 'The "One-Pan" Dinner',
            niche: 'Food & Cooking',
            description: 'Simple, delicious recipes that only require a single pan, tapping into the demand for low-effort meals.',
            platform: 'TikTok',
            viralityScore: 88,
            isBreakoutTrend: false,
            hashtags: '#onepanmeal, #easyrecipe, #tiktokfood',
            reasoning: 'This trend taps into the universal desire for convenience and minimal cleanup, making it highly relatable and shareable for busy people.',
            googleTrendsLink: 'https://trends.google.com/trends/explore?q=one%20pan%20meals',
            viralAudioSound: 'Aesthetic - Tollan Kim',
            postPlan: {
                hook: 'Dinner for tonight with only ONE pan to wash.',
                caption: 'This one-pan chicken and veggie recipe is a weeknight game-changer. So easy and so delicious!',
                emojiCombo: '🍳🥘😋',
                suggestedPostFormat: 'TikTok Video',
            }
        },
        {
            trendName: 'Vintage Streetwear Finds',
            niche: 'Fashion',
            description: 'Thrift hauls and styling videos focused on 90s and Y2K streetwear are dominating fashion feeds.',
            platform: 'Instagram Reels',
            viralityScore: 85,
            isBreakoutTrend: false,
            hashtags: '#vintagefashion, #thrifthaul, #90sstyle',
            reasoning: 'A combination of nostalgia for the 90s/Y2K era and a growing interest in sustainable fashion has made thrifting cool again.',
            googleTrendsLink: 'https://trends.google.com/trends/explore?q=vintage%20streetwear',
            viralAudioSound: 'Original audio - creators talking about their finds',
            postPlan: {
                hook: 'You won\'t believe what I found at the thrift store today.',
                caption: 'Styling my latest vintage streetwear finds. Which outfit is your favorite? 1, 2, or 3?',
                emojiCombo: '👟♻️🔥',
                suggestedPostFormat: 'Instagram Reel',
            }
        },
        {
            trendName: 'Cozy Gaming Setups',
            niche: 'Gaming',
            description: 'Gamers are showcasing their aesthetic and cozy gaming setups, focusing on ambiance, lighting, and comfort.',
            platform: 'TikTok',
            viralityScore: 82,
            isBreakoutTrend: false,
            hashtags: '#cozygaming, #gamingsetup, #desksetup',
            reasoning: 'As gaming becomes more mainstream, the focus is shifting from pure performance to creating a personalized and comfortable environment.',
            googleTrendsLink: 'https://trends.google.com/trends/explore?q=cozy%20gaming%20setup',
            viralAudioSound: 'Lofi Girl - A Place to Study',
            postPlan: {
                hook: 'My gaming setup is my happy place.',
                caption: 'Come build my new cozy gaming setup with me! Let me know what you think of the final result.',
                emojiCombo: '🎮💖🌙',
                suggestedPostFormat: 'TikTok Video',
            }
        },
        {
            trendName: '"BookTok" Made Me Buy It',
            niche: 'Books & Literature',
            description: 'Readers are sharing their book hauls and reviews, driven by recommendations from the #BookTok community.',
            platform: 'TikTok',
            viralityScore: 90,
            isBreakoutTrend: true,
            hashtags: '#booktok, #bookhaul, #tbr',
            reasoning: 'The #BookTok community has become a powerful force in the publishing industry, driving massive sales for recommended titles.',
            googleTrendsLink: 'https://trends.google.com/trends/explore?q=booktok',
            viralAudioSound: 'original audio - book reviews',
            postPlan: {
                hook: '5 books BookTok convinced me to buy.',
                caption: 'My latest book haul is 100% influenced by BookTok. Have you read any of these? No spoilers!',
                emojiCombo: '📚🛒❤️',
                suggestedPostFormat: 'TikTok Video',
            }
        },
        {
            trendName: 'The 30-Day DIY Challenge',
            niche: 'DIY & Crafts',
            description: 'Creators are challenging themselves to complete a new DIY project every day for 30 days, showing the process.',
            platform: 'YouTube Shorts',
            viralityScore: 78,
            isBreakoutTrend: false,
            hashtags: '#diychallenge, #30daychallenge, #crafting',
            reasoning: 'This trend combines the satisfaction of a challenge with the appeal of before-and-after transformations, making it highly engaging.',
            googleTrendsLink: 'https://trends.google.com/trends/explore?q=diy%20challenge',
            viralAudioSound: 'Upbeat and motivational instrumental music',
            postPlan: {
                hook: 'I decided to do one DIY project every day for a month.',
                caption: 'Day 1 of my 30-day DIY challenge! Today, we\'re making... Follow along to see if I can do it!',
                emojiCombo: '🛠️🗓️💪',
                suggestedPostFormat: 'YouTube Short',
            }
        },
        {
            trendName: 'Mindful Morning Routines',
            niche: 'Health & Wellness',
            description: 'Instead of hustle culture, creators are sharing slow, mindful morning routines focusing on journaling, meditation, and gratitude.',
            platform: 'Instagram Reels',
            viralityScore: 84,
            isBreakoutTrend: false,
            hashtags: '#mindfulmorning, #slowliving, #wellnessroutine',
            reasoning: 'There is a growing counter-movement against "hustle culture," with people seeking more balance and mental peace.',
            googleTrendsLink: 'https://trends.google.com/trends/explore?q=mindful%20morning%20routine',
            viralAudioSound: 'Peaceful acoustic music',
            postPlan: {
                hook: 'My 5 AM morning routine that isn\'t about productivity.',
                caption: 'Starting the day with intention, not pressure. My mindful morning routine has changed everything.',
                emojiCombo: '☀️🧘‍♀️📓',
                suggestedPostFormat: 'Instagram Reel',
            }
        },
        {
            trendName: 'EV Road Trips',
            niche: 'Automotive',
            description: 'Showcasing the experience of a long-distance road trip in an electric vehicle, addressing range anxiety and charging.',
            platform: 'YouTube',
            viralityScore: 75,
            isBreakoutTrend: false,
            hashtags: '#evroadtrip, #electricvehicle, #roadtrip',
            reasoning: 'As electric vehicles become more common, potential buyers are curious about their real-world long-distance capabilities.',
            googleTrendsLink: 'https://trends.google.com/trends/explore?q=ev%20road%20trip',
            viralAudioSound: 'Upbeat travel vlogging music',
            postPlan: {
                hook: 'We drove a Tesla 1,000 miles. Here\'s what happened.',
                caption: 'Can you really road trip in an EV? We put it to the test on a cross-country adventure.',
                emojiCombo: '🚗⚡️🗺️',
                suggestedPostFormat: 'YouTube Video',
            }
        }
    ]
};

const cache = new Map<string, {
    timestamp: number;
    data: TopTrendsOutput;
}>();

const CACHE_DURATION_MS = 5 * 60 * 1000; // 5 minutes

export async function getTopTrends(input: TopTrendsInput): Promise<TopTrendsOutput> {
  return topTrendsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'topTrendsPrompt',
  input: { schema: z.object({ nicheList: z.array(z.string()), region: z.string() }) },
  output: { schema: TopTrendsOutputSchema },
  templateFormat: 'handlebars',
  prompt: `You are a social media trend expert and data analyst with access to real-time social data for the specified region.

Your task is to identify emerging trends for the **{{region}}** region for each of the following niches. You MUST return at least TWO trends for each niche provided.

Niches:
{{#each nicheList}}
- {{this}}
{{/each}}


For each trend, you must provide a comprehensive analysis. Your output must be a JSON object containing a list of trends, and each trend object must include:
1.  **trendName**: The name of the trend.
2.  **niche**: The niche it belongs to (must be one of the provided niches).
3.  **description**: A short, compelling one-sentence explanation of the trend.
4.  **platform**: The main platform where it is currently trending in {{region}}.
5.  **viralityScore**: A 0-100 score of its current viral potential in {{region}}.
6.  **isBreakoutTrend**: A boolean. Set this to true ONLY for trends experiencing explosive, rapid growth in the last 24-48 hours. Be selective; most trends should have this set to false.
7.  **hashtags**: A comma-separated string of 3-5 relevant hashtags.
8.  **reasoning**: A detailed explanation for why the trend is rising (cultural context, events, etc.).
9.  **googleTrendsLink**: A full, working Google Trends URL for a relevant keyword, ideally localized for {{region}}.
10. **viralAudioSound**: If applicable, the name of a viral audio associated with the trend.
11. **postPlan**: A complete AI-powered post plan including a hook, caption, emoji combo, and suggested format.

Your response must be in JSON format.`,
});

const topTrendsFlow = ai.defineFlow(
  {
    name: 'topTrendsFlow',
    inputSchema: TopTrendsInputSchema,
    outputSchema: TopTrendsOutputSchema,
  },
  async ({ region }) => {
    const now = Date.now();
    const cachedEntry = cache.get(region);

    if (cachedEntry && (now - cachedEntry.timestamp < CACHE_DURATION_MS)) {
        console.log(`Returning cached top trends for ${region}.`);
        return cachedEntry.data;
    }

    try {
        const nicheList = niches.map(n => n.name);
        const {output} = await prompt({ nicheList, region });
        
        if (!output || !output.trends || output.trends.length === 0) {
            console.warn(`AI returned no trends for ${region}, using fallback.`);
            return fallbackTrends;
        }

        console.log(`Fetched new top trends for ${region}, updating cache.`);
        cache.set(region, {
            timestamp: now,
            data: output,
        });

        return output;
    } catch (error) {
        console.warn(`Error fetching top trends from AI for ${region}, using fallback:`, error);
        return fallbackTrends;
    }
  }
);

    