
'use server';

/**
 * @fileOverview An AI agent that identifies the top trending topics across various niches,
 * including a full post plan for each.
 *
 * - getTopTrends - A function that returns a list of top trends with all details.
 * - TopTrendsOutput - The return type for the getTopTrends function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TrendSchema = z.object({
    trendName: z.string().describe('The name of the emerging trend.'),
    niche: z.string().describe('The content niche this trend belongs to (e.g., Fashion, Gaming, Food).'),
    description: z.string().describe('A brief, one-sentence description of the trend and why it\'s popular.'),
    platform: z.string().describe('The primary social media platform where this trend is popular (e.g., TikTok, Instagram).'),
    viralityScore: z.number().min(0).max(100).describe('A score from 0-100 indicating the trend\'s current virality.'),
    hashtags: z.string().describe('A string of 3-5 relevant hashtags, separated by commas (e.g., #AIart, #generativeart, #digitalart).'),
    reasoning: z.string().describe('A detailed explanation of why the trend is rising, citing cultural context, events, or other factors.'),
    googleTrendsLink: z.string().describe('A full, working URL to the Google Trends page for a relevant keyword.'),
    viralAudioSound: z.string().optional().describe('The name or ID of a viral audio/sound associated with the trend, if applicable.'),
    postPlan: z.object({
        hook: z.string().describe('A captivating hook for the post.'),
        caption: z.string().describe('An engaging caption for the post.'),
        emojiCombo: z.string().describe('A creative combination of emojis for the post.'),
        suggestedPostFormat: z.string().describe('The suggested post format (e.g., Reel, meme, tweet).'),
    }).describe('A full AI-powered post plan for this trend.')
});

const TopTrendsOutputSchema = z.object({
  trends: z.array(TrendSchema).describe('A list of 12-15 diverse, top-trending topics across different popular niches, with full post plans and analysis for each.'),
});
export type TopTrendsOutput = z.infer<typeof TopTrendsOutputSchema>;
export type Trend = z.infer<typeof TrendSchema>;

const fallbackTrends: TopTrendsOutput = {
    trends: [
        {
            trendName: 'AI-Generated Art',
            niche: 'AI & Future Tech',
            description: 'Creators are using AI to generate surreal and stunning visuals, pushing the boundaries of creativity.',
            platform: 'Instagram',
            viralityScore: 92,
            hashtags: '#AIart, #generativeart, #digitalart',
            reasoning: 'Advances in text-to-image models have made high-quality AI art accessible to everyone, leading to a Cambrian explosion of creativity.',
            googleTrendsLink: 'https://trends.google.com/trends/explore?q=ai%20art',
            viralAudioSound: 'Metamorphosis - INTERWORLD',
            postPlan: {
                hook: 'I asked an AI to paint a dream...',
                caption: 'Exploring the surreal landscapes generated by AI. What does the future of art look like? #AIart',
                emojiCombo: '🤖🎨✨',
                suggestedPostFormat: 'Instagram Carousel Post',
            }
        },
        {
            trendName: 'The "One-Pan" Dinner',
            niche: 'Food & Cooking',
            description: 'Simple, delicious recipes that only require a single pan, tapping into the demand for low-effort meals.',
            platform: 'TikTok',
            viralityScore: 88,
            hashtags: '#onepanmeal, #easyrecipe, #tiktokfood',
            reasoning: 'This trend taps into the universal desire for convenience and minimal cleanup, making it highly relatable and shareable for busy people.',
            googleTrendsLink: 'https://trends.google.com/trends/explore?q=one%20pan%20meals',
            viralAudioSound: 'Aesthetic - Tollan Kim',
            postPlan: {
                hook: 'Dinner for tonight with only ONE pan to wash.',
                caption: 'This one-pan chicken and veggie recipe is a weeknight game-changer. So easy and so delicious!',
                emojiCombo: '🍳🥘😋',
                suggestedPostFormat: 'TikTok Video',
            }
        },
        {
            trendName: 'Vintage Streetwear Finds',
            niche: 'Fashion',
            description: 'Thrift hauls and styling videos focused on 90s and Y2K streetwear are dominating fashion feeds.',
            platform: 'Instagram Reels',
            viralityScore: 85,
            hashtags: '#vintagefashion, #thrifthaul, #90sstyle',
            reasoning: 'A combination of nostalgia for the 90s/Y2K era and a growing interest in sustainable fashion has made thrifting cool again.',
            googleTrendsLink: 'https://trends.google.com/trends/explore?q=vintage%20streetwear',
            viralAudioSound: 'Original audio - creators talking about their finds',
            postPlan: {
                hook: 'You won\'t believe what I found at the thrift store today.',
                caption: 'Styling my latest vintage streetwear finds. Which outfit is your favorite? 1, 2, or 3?',
                emojiCombo: '👟♻️🔥',
                suggestedPostFormat: 'Instagram Reel',
            }
        },
    ]
};


export async function getTopTrends(): Promise<TopTrendsOutput> {
  return topTrendsFlow();
}

const prompt = ai.definePrompt({
  name: 'topTrendsPrompt',
  output: {schema: TopTrendsOutputSchema},
  prompt: `You are a social media trend expert and data analyst with access to real-time social data.

Your task is to identify the top 12-15 emerging trends across a wide variety of popular niches. Ensure you provide a diverse mix from categories like: AI & Future Tech, Automotive, Beauty, Books & Literature, Business & Entrepreneurship, Comedy, Dance, DIY & Crafts, Education, Fashion, Finance & Investing, Food & Cooking, Gaming, Health & Wellness, Home & Garden, Movies & TV, Music, Parenting, Pets, Real Estate, Relationships & Dating, Science & Nature, Sports, Spirituality & Mindfulness, Tech, Travel, and ASMR.

For each trend, you must provide a comprehensive analysis. Your output must be a JSON object containing a list of trends, and each trend object must include:
1.  **trendName**: The name of the trend.
2.  **niche**: The niche it belongs to.
3.  **description**: A short, compelling one-sentence explanation of the trend.
4.  **platform**: The main platform where it is currently trending.
5.  **viralityScore**: A 0-100 score of its current viral potential.
6.  **hashtags**: A comma-separated string of 3-5 relevant hashtags.
7.  **reasoning**: A detailed explanation for why the trend is rising (cultural context, events, etc.).
8.  **googleTrendsLink**: A full, working Google Trends URL for a relevant keyword.
9.  **viralAudioSound**: If applicable, the name of a viral audio associated with the trend.
10. **postPlan**: A complete AI-powered post plan including a hook, caption, emoji combo, and suggested format.

Your response must be in JSON format.`,
});

const topTrendsFlow = ai.defineFlow(
  {
    name: 'topTrendsFlow',
    outputSchema: TopTrendsOutputSchema,
  },
  async () => {
    try {
        const {output} = await prompt();
        if (!output || !output.trends || output.trends.length === 0) {
            console.warn('AI returned no trends, using fallback.');
            return fallbackTrends;
        }
        return output;
    } catch (error) {
        console.warn('Error fetching top trends from AI, using fallback:', error);
        return fallbackTrends;
    }
  }
);
